// Test fixture for Carbide's source-generator support (M12). Not shipped — Carbide's tests
// read the built DLL's bytes and register it with `session.addAnalyzer`.
//
// This is deliberately a *real* incremental generator rather than a single unconditional
// AddSource, because the three things Carbide has to get right are exactly the three things
// a trivial generator would not exercise:
//
//   1. post-initialization output — source the generator contributes before it has seen any
//      user code, which user code then compiles against (here, the marker attribute);
//   2. a syntax provider plus a semantic model — the generator has to be able to ask Roslyn
//      questions about the user's compilation;
//   3. output that participates in the emitted assembly, not just in diagnostics.
//
// Applying [GenerateToString] to a partial class produces a ToString override listing the
// class's public instance properties.

using System.Collections.Generic;
using System.Linq;
using System.Text;
using Microsoft.CodeAnalysis;
using Microsoft.CodeAnalysis.CSharp.Syntax;
using Microsoft.CodeAnalysis.Text;

namespace CarbideTestGenerator;

[Generator]
public sealed class GenerateToStringGenerator : IIncrementalGenerator
{
    private const string AttributeName = "CarbideTest.GenerateToStringAttribute";

    private const string AttributeSource = """
        // <auto-generated/>
        namespace CarbideTest
        {
            [global::System.AttributeUsage(global::System.AttributeTargets.Class, AllowMultiple = false)]
            internal sealed class GenerateToStringAttribute : global::System.Attribute
            {
            }
        }
        """;

    public void Initialize(IncrementalGeneratorInitializationContext context)
    {
        context.RegisterPostInitializationOutput(ctx => ctx.AddSource(
            "CarbideTest.GenerateToStringAttribute.g.cs",
            SourceText.From(AttributeSource, Encoding.UTF8)));

        var targets = context.SyntaxProvider.ForAttributeWithMetadataName(
            AttributeName,
            predicate: static (node, _) => node is ClassDeclarationSyntax,
            transform: static (ctx, _) => (INamedTypeSymbol)ctx.TargetSymbol);

        context.RegisterSourceOutput(targets, static (ctx, symbol) =>
        {
            var properties = symbol.GetMembers()
                .OfType<IPropertySymbol>()
                .Where(p => !p.IsStatic
                            && p.DeclaredAccessibility == Accessibility.Public
                            && p.GetMethod is not null)
                .Select(p => p.Name)
                .ToList();

            ctx.AddSource(
                $"{symbol.Name}.ToString.g.cs",
                SourceText.From(Render(symbol, properties), Encoding.UTF8));
        });
    }

    private static string Render(INamedTypeSymbol symbol, IReadOnlyList<string> properties)
    {
        var body = properties.Count == 0
            ? $"\"{symbol.Name} {{ }}\""
            : "\"" + symbol.Name + " { \" + " +
              string.Join(" + \", \" + ", properties.Select(p => $"\"{p} = \" + this.{p}")) +
              " + \" }\"";

        var ns = symbol.ContainingNamespace.IsGlobalNamespace
            ? null
            : symbol.ContainingNamespace.ToDisplayString();

        var sb = new StringBuilder();
        sb.AppendLine("// <auto-generated/>");
        if (ns is not null)
        {
            sb.AppendLine($"namespace {ns}");
            sb.AppendLine("{");
        }
        sb.AppendLine($"    partial class {symbol.Name}");
        sb.AppendLine("    {");
        sb.AppendLine("        public override string ToString() =>");
        sb.AppendLine($"            {body};");
        sb.AppendLine("    }");
        if (ns is not null)
        {
            sb.AppendLine("}");
        }
        return sb.ToString();
    }
}
