// UI-M4 (plan §8, proposal §9.1): generates a C# companion for an .axaml source so
// user-written `public partial class MyView : UserControl { public MyView() {
// InitializeComponent(); } }` compiles unchanged and renders the XAML at runtime
// via AvaloniaRuntimeXamlLoader.
//
// The companion is a thin generated file paired with the .axaml by ProjectCompiler.
// UI-M7 will replace it with Avalonia's compile-time XAML source generator (gated on
// Carbide M12). Runtime parse cost is microseconds for typical views — proposal §9.2
// notes this as acceptable for the v1 "95% solution".

using System.Text;
using System.Text.RegularExpressions;

namespace Carbide.Core.Services;

internal static partial class AxamlCompanionGenerator
{
    /// <summary>
    /// Produces the C# companion source for a .axaml document, or <c>null</c> when the
    /// XAML root does not declare an <c>x:Class</c> attribute. Callers that get null
    /// should not add a companion document — the .axaml is still addressable via
    /// explicit <see cref="Avalonia.Markup.Xaml.AvaloniaRuntimeXamlLoader.Load(string, System.Reflection.Assembly?, object?, System.Uri?, bool)"/>
    /// calls from user code.
    /// </summary>
    /// <param name="axamlPath">Document path (used only in a header comment for traceability).</param>
    /// <param name="xaml">Raw XAML source.</param>
    public static string? Generate(string axamlPath, string xaml)
    {
        var xClass = ExtractXClass(xaml);
        if (xClass is null) return null;
        var (ns, cls) = SplitFqName(xClass);

        var sb = new StringBuilder();
        sb.Append("// <auto-generated>Carbide UI-M4 companion for ").Append(axamlPath).AppendLine("</auto-generated>");
        sb.AppendLine("#pragma warning disable");
        sb.AppendLine("#nullable disable");
        if (!string.IsNullOrEmpty(ns))
        {
            sb.Append("namespace ").Append(ns).AppendLine(";");
            sb.AppendLine();
        }
        sb.Append("partial class ").AppendLine(cls);
        sb.AppendLine("{");
        sb.Append("    private const string __CarbideAxaml = @\"");
        sb.Append(xaml.Replace("\"", "\"\""));
        sb.AppendLine("\";");
        sb.AppendLine();
        sb.AppendLine("    public void InitializeComponent()");
        sb.AppendLine("    {");
        sb.Append("        global::Avalonia.Markup.Xaml.AvaloniaRuntimeXamlLoader.Load(__CarbideAxaml, typeof(");
        sb.Append(cls);
        sb.AppendLine(").Assembly, this);");
        sb.AppendLine("    }");
        sb.AppendLine("}");
        return sb.ToString();
    }

    /// <summary>
    /// Appends <c>.g.cs</c> to the original .axaml path; used as the paired document's
    /// key in <see cref="ProjectCompiler"/>'s solution so Roslyn treats the companion
    /// as a sibling source file.
    /// </summary>
    public static string CompanionPath(string axamlPath) => axamlPath + ".g.cs";

    // x:Class is the only XAML attribute we need; a full XML parse would pull in an
    // unnecessary dependency. Tolerates single- or double-quoted values and whitespace
    // around the = sign. Assumes the attribute appears on the root element (Avalonia's
    // convention); any occurrence in the first 16 KB wins.
    [GeneratedRegex(@"x:Class\s*=\s*(?:""([^""]*)""|'([^']*)')", RegexOptions.CultureInvariant)]
    private static partial Regex XClassRegex();

    private static string? ExtractXClass(string xaml)
    {
        var m = XClassRegex().Match(xaml, 0, Math.Min(xaml.Length, 16 * 1024));
        if (!m.Success) return null;
        var v = m.Groups[1].Value;
        return string.IsNullOrEmpty(v) ? m.Groups[2].Value : v;
    }

    private static (string Namespace, string Class) SplitFqName(string fqName)
    {
        var idx = fqName.LastIndexOf('.');
        return idx < 0
            ? (string.Empty, fqName)
            : (fqName[..idx], fqName[(idx + 1)..]);
    }
}
